### ISSUE TITLE
can't resize video

### ISSUE THREAD

**Issue by Yay295** [Dador/JavascriptSubtitlesOctopus#1]
After the instance has been created, the video cannot be resized or moved; or rather, resizing or moving the video does not affect the position of the subtitles. If the video is made fullscreen, the subtitles are completely hidden.

If you use the video.js version you can make it fullscreen, but you can't un-fullscreen it (the subtitles, that is).

**Comment by Dador** [comment]
> If the video is made fullscreen, the subtitles are completely hidden.
That happens because browser fullscreens exactly video element (and nothing outside), so there is no way to put anything above video.
This could be overcome if we could prevent "fullscreenchange" event and fullscreen parent element instead. But sadly fullscreenchange couldn't be prevented and even if it is, fullscreen should be called as result of user input.
So, that can't be fixed without custom controls. Fortunately most players use their own custom controls.

> If you use the video.js version you can make it fullscreen, but you can't un-fullscreen it (the subtitles, that is).
Yep, that's was already fixed. Just forgot to update demo :)
Please check https://dador.github.io/JavascriptSubtitlesOctopus/videojs.html

**Comment by Yay295** [comment]
So if I wanted to resize the video, or move it, how could I do that and keep the subtitles in the right place?

ps: Your demo video is 4 seconds too short.

**Comment by Dador** [comment]
> So if I wanted to resize the video, or move it, how could I do that and keep the subtitles in the right place?

You can call [.resize()](https://github.com/Dador/JavascriptSubtitlesOctopus/blob/master/js/subtitles-octopus.js#L313) after resizing, for example:
```javascript
var instance = new SubtitlesOctopus(options);

// ...resize video...

// Call .resize()
instance.resize();
// You can also specify width and height (for example if you rendering without video)
instance.resize(1280, 720);
```
There is no event for element resize so you should call it manually (also it called automatically in case of window resize and fullscreenchange events).

> ps: Your demo video is 4 seconds too short.

Yep, need to find longer video (hosted and available for streaming).
