### ISSUE TITLE
Character ☆ not being rendered properly

### ISSUE THREAD

**Issue by nickfujita** [Dador/JavascriptSubtitlesOctopus#21]
When a file contains the ☆ character, the library appears to be rendering it as a square:

![image](https://user-images.githubusercontent.com/6342442/35381280-15e774f8-01ff-11e8-809e-da4069e80b10.png)

Instead of sending in a url first download the content to a string, confirmed that the ☆ character is preserved, and then passed it into the library as content. This didn't work. While looking thought the code in the library it appears that the content are being written to a `.ass` file to be used by the worker for rendering. At some point, it appears that the utf-8 encoding is lost, either in the write/read of this file, or by the rendering engine.

**Comment by Dador** [comment]
This happens because "☆" is not included in Arial (which is used as default font). Fonts that covers almost all possible symbols typically quite large (for example "Arial Unicode MS" is around 22MB) and that is the reason why such fonts not used as default.

But in case with that ☆ symbol, you can use symbol font, such as "Segoe UI Symbol". Probably just adding it (i.e. adding link to it to list of fonts) will work.

**Comment by nickfujita** [comment]
According to [this](http://www.fileformat.info/info/unicode/char/2606/fontsupport.htm) ☆ is not in Arial, but it's strange that in Aegisub it renders fine.

![image](https://user-images.githubusercontent.com/6342442/35425905-0b720f44-02a2-11e8-89eb-1c54ad892498.png)

**Comment by nickfujita** [comment]
Confirmed working when passing Arial Unicode MS in. Closing. Thanks for the help as always :)
