### ISSUE TITLE
Refused to execute script from 

### ISSUE THREAD

**Issue by SelfEnough** [Dador/JavascriptSubtitlesOctopus#26]
I use raw url to my page but it shows：
Refused to execute script from 'https://raw.githubusercontent.com/Dador/JavascriptSubtitlesOctopus/master/js/asmjs/subtitles-octopus.js' because its MIME type ('text/plain') is not executable, and strict MIME type checking is enabled.

**Comment by Dador** [comment]
I recommend you to download file and store it on your server. Because project is quite experimental some API or details can be changed in the future, so if you use script directly from github then your script could became broken.

Also you can try https://rawgit.com/ but as I said it's not recommended and probably you'll have to change path to fonts & data.
