### ISSUE TITLE
Docker Image for Easily Reproducible Builds

### ISSUE THREAD

**Issue by johnhenry** [Dador/JavascriptSubtitlesOctopus#28]
Hi @Dador! Thanks for building and maintaining such a useful library.
I've been trying to make changes and I've been running into various  compilation issue. I wonder if you've ever considered setting up a Docker image for easily reducible builds?

**Comment by Dador** [comment]
Hi!
Sadly, but currently I'm not able to maintain this project.
You can take a look on relatively active fork: https://github.com/TFSThiagoBR98/JavascriptSubtitlesOctopus, maybe it would be more helpful for you.

**Comment by cobarx** [comment]
Hi @Dador, I'm a colleague of @johnhenry at Crunchyroll. Thanks for the pointer to the other project! We were able to get it to build and so far it's looking good.

Since it sounds like you are short on time, would you be interested in allowing us to be maintainers and merge patches? I think it would be good to maintain the central repo so that people don't get confused about which project to use. It might also be good to include @TFSThiagoBR98 as well since he has been making a lot of improvements to the build processes. 

Thank you for all your hard work on this library, it's amazing!

**Comment by johnhenry** [comment]
@Dador thanks for the tip!

**Comment by Dador** [comment]
> Since it sounds like you are short on time, would you be interested in allowing us to be maintainers and merge patches? 

It's good idea. I invited you @cobarx, @TFSThiagoBR98, and @johnhenry as maintainers. I merged changes from @TFSThiagoBR98. Feel free to add features you'll find useful.

It's nice idea to use Docker for this project, so I reopen this issue.
